name: Kernel Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v3

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y bc bison flex libssl-dev make libc6-dev libncurses5-dev gcc git wget cpio python3 unzip

    - name: Download and extract Proton Clang
      run: |
        mkdir -p clang
        curl -LO https://gitlab.com/baalajimaestro/proton-clang/-/archive/20240501/proton-clang-20240501.tar.gz
        tar -xvzf proton-clang-20240501.tar.gz -C clang --strip-components=1

    - name: Set environment variables
      run: |
        export PATH=$GITHUB_WORKSPACE/clang/bin:$PATH
        export CLANG_TRIPLE=aarch64-linux-gnu-
        export CROSS_COMPILE=aarch64-linux-android-
        export CROSS_COMPILE_ARM32=arm-linux-androideabi-
        echo "PATH=$GITHUB_WORKSPACE/clang/bin:$PATH" >> $GITHUB_ENV
        echo "CLANG_TRIPLE=aarch64-linux-gnu-" >> $GITHUB_ENV
        echo "CROSS_COMPILE=aarch64-linux-android-" >> $GITHUB_ENV
        echo "CROSS_COMPILE_ARM32=arm-linux-androideabi-" >> $GITHUB_ENV

    - name: Build kernel
      run: |
        mkdir -p out
        make O=out ARCH=arm64 deconfig1
        make -j$(nproc) O=out ARCH=arm64 CC=clang

    - name: Upload drivers (.ko files)
      uses: actions/upload-artifact@v3
      with:
        name: kernel-modules
        path: |
          out/**/*.ko

    - name: Upload Module.symvers
      uses: actions/upload-artifact@v3
      with:
        name: Module.symvers
        path: out/Module.symvers
